### ISSUE TITLE
SQLiteError: no such table: _mf_objects

### ISSUE THREAD

**Issue by marcbejar** [emilienbidet/cloudflare-r2-dev-server#1]
Hi! thanks for your effort. I really apreciate it .

I followed all the instructions but when I try acces to a file it throws an Sqlite error:
SQLiteError: no such table: _mf_objects

Found this to be the origin of the query error:
![image](https://github.com/user-attachments/assets/ebd4f80b-6e1c-4138-aeaf-f116897d63b0)

-------------------------------------------------  ### **EDIT** 
Found the problem, In the docs, the db env name is incorrect -> R2_BUCKET_DABASE_NAME shoud be R2_BUCKET_DATABASE_NAME :)

**Comment by emilienbidet** [comment]
Rhaagg thank you very much for opening an issue. I will fix it now. Thank you @marcbejar !!
